### ISSUE TITLE
PhraseExpress - .msi file is wrong version causing installation failure.  .exe is correct version

### ISSUE THREAD

**Issue by virtualex-itv** [bc3tech/chocolatey#15]
This package downloads an `.msi` file which is actually not available on their website.  The site only provides you with an `.exe` but if you change the download URL to grab the `.msi` file, it does indeed download.  The problem is see is that the `.msi` file is actually version `15.0.81` where as the .exe version is `15.0.84`.  I think it would be best to update this package to use the .exe file going forward to prevent issues down the road.

I've messaged you in Slack as well and provided you with updated `.nupkg` files using the `.exe` so you make revisions to the current packages, tested and working...

![choco-phraseexpress-test](https://user-images.githubusercontent.com/12056704/107669648-f3a06480-6c5f-11eb-9ad8-008e78b0d2a4.png)

**Comment by bc3tech** [comment]
could you just submit the updates as a PR? Thanks.

**Comment by bc3tech** [comment]
I see where you're coming from, however this is a bug on PhraseExpress' end and they still offer the MSI for download from the location I'm targeting.
![image](https://user-images.githubusercontent.com/1967433/107809936-bcde5300-6d20-11eb-9312-b8a8252db876.png)

If the EXE cannot be silently installed (as is the desire for Chocolatey packages) then this procedure is still correct, and PE needs to fix their release mechanism. Was your .exe install able to be made silent?

It's worth noting the portable installer they have released is v.84 as desired.

**Comment by virtualex-itv** [comment]
Hey Brandon - i took a look at the repo but it appears this package is
using all sorts of variables in certain fields so I don't think I can
submit a PR without knowing where the variable is reading.

It looks like phraseexpress updated the site and now the .msi version is at
the correct .84 version.  if you'd like, please simply update the file hash
and increment the package version before submitting again.  The correct
sha256 hash for the new msi is:

*84F077781B018C4354BB1DD9D828F610C3528686C149768EF9CABAE6666B6174*

*If you'd like to let me know once an update has been pushed, I'll moderate
the package.*

*Alex*
*Chocolatey Moderator*

**Comment by bc3tech** [comment]
can't resubmit:
```
2021-03-05T23:59:56.7685644Z Pushing: D:\a\r1\a\PhraseExpressReleases\drop\phraseexpress.15.0.84.nupkg ...
2021-03-05T23:59:58.0809834Z Chocolatey v0.10.15
2021-03-06T00:01:13.1700259Z Attempting to push phraseexpress.15.0.84.nupkg to https://push.chocolatey.org
2021-03-06T00:01:14.1986279Z An error has occurred. It's possible the package version already exists on the repository.
2021-03-06T00:01:14.2691045Z Pushing: D:\a\r1\a\PhraseExpressReleases\drop\phraseexpress.install.15.0.84.nupkg ...
2021-03-06T00:01:14.7614647Z Chocolatey v0.10.15
2021-03-06T00:01:15.3334238Z Attempting to push phraseexpress.install.15.0.84.nupkg to https://push.chocolatey.org
2021-03-06T00:01:15.9526498Z An error has occurred. It's possible the package version already exists on the repository.
2021-03-06T00:01:15.9828211Z Pushing: D:\a\r1\a\PhraseExpressReleases\drop\phraseexpress.portable.15.0.84.nupkg ...
2021-03-06T00:01:16.4445941Z Chocolatey v0.10.15
2021-03-06T00:01:17.0085127Z Attempting to push phraseexpress.portable.15.0.84.nupkg to https://push.chocolatey.org
2021-03-06T00:01:17.6905695Z An error has occurred. It's possible the package version already exists on the repository.
```

**Comment by bc3tech** [comment]
Submitted as 15.0.84.1

**Comment by virtualex-itv** [comment]
Hey Brandon - looks like the new package has failed automated testing and
upon further inspection of the log file, it's still using the wrong hash
(see below).  Possibly you forgot to update the hash before resubmitting?

Running Install-ChocolateyPackage -url '
https://www.phraseexpress.com/PhraseExpressSetup.msi' -url64bit '
https://www.phraseexpress.com/PhraseExpressSetup.msi' -checksum
'2188805F89F02E6A0731A833A8DF02F09A372D36170D6EF0E3779972D1A713C8'
-checksumType 'sha256' -packageName 'PhraseExpress.Install' -fileType 'MSI'
-validExitCodes '0 3010 1641' -silentArgs '/qn /norestart /l*v
"C:\Users\Administrator\AppData\Local\Temp\chocolatey\PhraseExpress.Install.15.0.84.1.MsiInstall.log"'


I went ahead and re-downloaded the file manually and checked the hash for
this file (see below)

Invoke-WebRequest -Uri https://www.phraseexpress.com/PhraseExpressSetup.msi
-OutFile C:\PhraseExpressSetup.msi
Get-FileHash -Path C:\PhraseExpressSetup.msi -Algorithm SHA256

Algorithm       Hash
            Path
---------       ----
            ----
SHA256
 84F077781B018C4354BB1DD9D828F610C3528686C149768EF9CABAE6666B6174
C:\PhraseExpressSetup.msi


Can you please update the hash per the above and resubmit vers 15.0.84.1
please and let me know?  I'll then check it out again...thanks!

Alex (virtualex)
Chocolatey Moderator

**Comment by bc3tech** [comment]
You're right. kicking off a new one now.

**Comment by virtualex-itv** [comment]
great!  it's still failing the automated testing but it's not due to an
issue with the updated package but rather an issue with the package
verifier.  I tested the install manually in a test environment and it
installed without issue.

Package Verifier - Could not create secure channel failure #11
<https://github.com/chocolatey/home/issues/11#issuecomment-792206986>
