### ISSUE TITLE
Greetings from ngrok

### ISSUE THREAD

**Issue by krwenholz** [bc3tech/chocolatey#22]
Hi there!

I work at ngrok and we're looking to start publishing more up-to-date versions of our binary. Thank you so much for getting the binary published to Chocolatey!

As part of getting more up to date binaries out in the world, we reached out to the Chocolatey folks about becoming package maintainers. They've granted that request at this point and we're ready to start pushing our binaries with each release (here in a few weeks or so). To keep things a little more official, we'd like to limit maintainers to ngrok employees. Would iit cause any disruption to remove you from the Chocolatey package? We have no intention of messing up your repo or anything and want to be polite about this.

Thanks again for your contributions and let us know if you have any questions!

**Comment by bc3tech** [comment]
done and done. Good to see y'all adopting chocolatey as a distro method 👍🏻👍🏻
