### ISSUE TITLE
Vivaldi package broken

### ISSUE THREAD

**Issue by pauby** [bc3tech/chocolatey#25]
The Vivaldi package just seems to be broken packages. All v5 stable ones are waiting on the maintainer fixing then up.

Can you look into this ASAP? There are a number of Disqus comments taking about this. I've also asked to be added as maintainer as there was no response to the email I sent last week (standard triage process).

Thanks.

**Comment by bc3tech** [comment]
Thanks. I've reached out to Vivaldi for information on what changed/how to fix it.

FWIW I received no email notifications from either Chocolatey.org or Disqus on this, and they all have the same e-mail address specified.

**Comment by pauby** [comment]
Any update on this?

**Comment by bc3tech** [comment]
[Nope](https://forum.vivaldi.net/post/557505)

**Comment by pauby** [comment]
Are you going to work towards fixing the package?

**Comment by bc3tech** [comment]
I require input from vivaldi to do so, hence the reason this issue is marked as `Blocked` and I provided a link to the support thread I started with them which has had no response.

**Comment by bc3tech** [comment]
Won't be fixing this since Paul & the admins saw fit to just reassign the entire package to him & take me off it. Future issues should be opened on [his repo](https://github.com/pauby/ChocoPackages/tree/master/automatic/vivaldi).
