### ISSUE TITLE
Albumstomp

### ISSUE THREAD

**Issue by tunisiano187** [bc3tech/chocolatey#28]
Hello, the Albumstomp package is outdated, can you update it ?
If now, i've prepared an auto updating version of it, so you can just add me as maintiner, and i'll do it.
chocolatey user : tunisiano

Thank you.

**Comment by bc3tech** [comment]
Thanks! I've added you as maintainer since i've pivoted my pkg installation platform to winget so no longer focus on maintaining these pkgs.
