### ISSUE TITLE
PhraseExpress package doesn't work anymore

### ISSUE THREAD

**Issue by Jackenmen** [bc3tech/chocolatey#7]

**Comment by bc3tech** [comment]
Could you provide some details? Like what you're seeing in chocolatey when you try?

**Comment by Jackenmen** [comment]
Sorry, I could have at least mentioned that your package fails automatical test run on chocolatey.org, my bad.
As for what I'm seeing - there's checksum mismatch:
Checksum that install scripts checks against:
`2711C4A6F6141F08155FDB707BC6A5F7F4388815786AB01A71F13684EA914747`
Actual value:
`A0963B0C57EF44FF0FCE5F3C47227AA77C63FDC25E43DEDD78E658E4028151ED`

After additional checking I see that PhraseExpress's developers just don't provide version-specific links and because your package is outdated, the checksum is no longer valid.

**Comment by bc3tech** [comment]
Found that my automation rule to create new versions (time-based because they don't publish version links as you said) was broken. I've fixed this and a new version is on it's way!
